stages:
  data_ingestion: #name of the component
    cmd: python src/data_ingestion.py #path of the component
    deps:
    - src/data_ingestion.py ##depends on itself(component)
    #params:
    #- data_ingestion.test_size
    outs:
    - data/raw #output of the data ingestion stage in folder data/raw
  data_preprocessing: #name of the component
    cmd: python src/data_preprocessing.py #path of the component
    deps:
    - data/raw #input of the data preprocessing stage is the output of the data ingestion stage
    - src/data_preprocessing.py ##depends on itself (component)
    outs: 
    - data/interim #output of the data preprocessing stage in folder data/interim
  feature_engineering: #name of the component
    cmd: python src/feature_engineering.py #path of the component
    deps:
    - data/interim #input of the feature engineering stage is the output of the data preprocessing stage
    - src/feature_engineering.py ##depends on itself (component)
    #params:
    #- feature_engineering.max_features
    outs:
    - data/processed #output of the feature engineering stage in folder data/processed
  model_building: #name of the component
    cmd: python src/model_building.py #path of the component
    deps:
    - data/processed #input of the model building stage is the output of the feature engineering stage
    - src/model_building.py ##depends on itself (component)
    #params:
    #- model_building.n_estimators
    #- model_building.random_state
    outs:
    - models/model.pkl
  model_evaluation: #name of the component
    cmd: python src/model_evaluation.py #path of the component
    deps:
    - models/model.pkl #input of the model evaluation stage is the output of the model building stage
    - src/model_evaluation.py ##depends on itself (component)
    metrics:
    - reports/metrics.json
